cache:
  yarn: true
  directories:
    - $HOME/cache
    - $HOME/.m2
services:
  - mysql
  - postgresql
matrix:
  include:
    - env: OPENRASP_LANG=java SERVER=tomcat8-jdk11
      language: java
      jdk: oraclejdk11
before_script:
  - bash ./travis/$OPENRASP_LANG/before_script.sh
script:
  - travis_retry bash ./travis/$OPENRASP_LANG/script.sh
