sudo: required
cache:
  directories:
    - $HOME/cache
matrix:
  include:
    - env: MSG=world CC=gcc-4.9 CXX=g++-4.9
      language: php
      php: 5.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    - env: MSG=world CC=gcc-4.9 CXX=g++-4.9
      language: php
      php: 5.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
before_install:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - pushd agent/php
  - wget -N https://packages.baidu.com/app/openrasp/libv8-5.9-linux.tar.gz -P $HOME/cache
  - tar -zxf $HOME/cache/libv8-5.9-linux.tar.gz
script:
  - NO_INTERACTION=1 REPORT_EXIT_STATUS=1 phpize && ./configure --with-v8=./libv8-5.9-linux --with-gettext && make && make test