version: '2'

services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.${SERVER}
    depends_on:
      - mysql
      - postgresql
      - sqlserver
      - oracle
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql5
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgresql9
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
  oracle:
    build:
      context: .
      dockerfile: Dockerfile.oracle